### ISSUE TITLE
Cannot pass paramTypes options

### ISSUE THREAD

**Issue by rdsedmundo** [un-ts/prettier#261] opened 2023-04-14 10:33 UTC
.prettierrc
```
  "overrides": [
    {
      "files": "*.sql",
      "options": {
          "numbered": [
            "$"
          ],
          "named": [
            ":"
          ]
        }
      }
    }
  ]
```

This throws:
> [error] Invalid paramTypes value. Expected , but received { numbered: ["$"], named: [":"] }.

A quick look in the [source code of the lib](https://github.com/ikatyang/vnopts#choiceschema) that Prettier uses, suggests that `value: Object` [as declared here](https://github.com/un-ts/prettier/blob/master/packages/sql/src/index.ts#L302) may not be a valid option.

**Comment by JounQin** [comment] 2023-04-14 10:35
Duplicate of #233

**Closed** 2023-04-14 10:35 UTC
