### ISSUE TITLE
`prettier --write .` cannot find `*.sh` files

### ISSUE THREAD

**Issue by felipecrs** [un-ts/prettier#281] opened 2023-08-26 18:09 UTC
```jsonc
// .prettierrc
{
  "tabWidth": 2,
  "useTabs": false,
  "plugins": ["prettier-plugin-sh"]
}
```

Still, when I run `prettier --write .`, Prettier formats all files but no `*.sh`. If I explicitly ask to format `*.sh`, then it works: `prettier --write . '**/*.sh'`.

I assumed that, with the plugin, Prettier would automatically discover the sh files?

**Comment by JounQin** [comment] 2023-08-27 02:55
Please provide a runnable reproduction.

**Comment by felipecrs** [comment] 2023-08-27 03:37
Sure:

```bash
git clone https://github.com/felipecrs/prettier-sh
cd prettier-sh
npm install
```

```console
❯ npx prettier --write .
.prettierrc 34ms
package-lock.json 4ms
package.json 1ms

> npx prettier --write . '**/*.sh'
.prettierrc 35ms
package-lock.json 4ms
package.json 1ms
test.sh 11ms
```

**Comment by JounQin** [comment] 2023-08-28 02:15
@felipecrs duplicate of https://github.com/prettier/prettier/issues/15079

**Closed by JounQin** 2023-08-28 02:15 UTC

**Comment by felipecrs** [comment] 2023-08-28 02:18
Oh, thank you!
